### PR TITLE
Fix appveyor config

### PR DESCRIPTION
**Pull request by davidanthoff**
Builds will still fail until the Snappy.jl stuff is merged, but we are getting very, very close and it would help if this is merged before we continue with the Snappy story.

### CODE REVIEW

**Comment by davidanthoff** [comment]
@tanmaykm Also, can you please switch appveyor on for this repo?

**Comment by tanmaykm** [comment]
I don't have privileges for that. Maybe @mdpradeep can?

**Comment by davidanthoff** [comment]
Bump, could this please be merged and appveyor be enabled? @ViralBShah do you know who can enable appveyor for this repo? Thanks!

**Comment by tanmaykm** [comment]
Merging it. Appveyor can be enabled separately.

**Pull request merged**
